import { defineQuestions } from "./define";

export const englishQuestions = defineQuestions("english", [
  // Concord
  {
    id: "eng-con-001",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: Neither the teacher nor the students ___ present.",
    options: ["was", "were", "is", "has been"],
    correctOption: 1,
    explanation: "With 'neither…nor', the verb agrees with the subject closest to it. 'Students' is plural, so the verb is 'were'.",
    difficulty: "medium",
  },
  {
    id: "eng-con-002",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: Each of the boys ___ given a book.",
    options: ["were", "are", "was", "have been"],
    correctOption: 2,
    explanation: "'Each' is the subject and it is singular, so it takes a singular verb: 'was'. The phrase 'of the boys' does not change this.",
    difficulty: "easy",
  },
  {
    id: "eng-con-003",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: The news ___ very encouraging.",
    options: ["are", "is", "were", "have been"],
    correctOption: 1,
    explanation: "'News' looks plural but is an uncountable noun and always takes a singular verb: 'The news is…'.",
    difficulty: "easy",
  },
  {
    id: "eng-con-004",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: Mathematics ___ my favourite subject.",
    options: ["is", "are", "were", "have been"],
    correctOption: 0,
    explanation: "Names of subjects ending in -s, such as Mathematics, Physics and Economics, are singular: 'Mathematics is…'.",
    difficulty: "easy",
  },
  {
    id: "eng-con-005",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: The committee ___ reached its decision.",
    options: ["have", "has", "are", "were"],
    correctOption: 1,
    explanation: "The possessive 'its' shows the committee is being treated as a single unit, so the singular verb 'has' is required.",
    difficulty: "medium",
  },
  {
    id: "eng-con-006",
    topicId: "concord",
    question: "Choose the option that best completes the sentence: One of the girls ___ lost her bag.",
    options: ["have", "has", "are", "were"],
    correctOption: 1,
    explanation: "The subject is 'one', which is singular. 'Of the girls' is just a phrase describing it, so the verb is 'has'.",
    difficulty: "easy",
  },

  // Tenses
  {
    id: "eng-ten-001",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: By the time we arrived, the film ___.",
    options: ["has started", "had started", "starts", "was start"],
    correctOption: 1,
    explanation: "The past perfect ('had started') shows an action completed before another past action ('we arrived').",
    difficulty: "medium",
  },
  {
    id: "eng-ten-002",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: She ___ in Kumasi since 2015.",
    options: ["lives", "is living", "has lived", "lived"],
    correctOption: 2,
    explanation: "'Since 2015' describes a situation that started in the past and continues now, which needs the present perfect: 'has lived'.",
    difficulty: "medium",
  },
  {
    id: "eng-ten-003",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: If I ___ you, I would apologise.",
    options: ["am", "was being", "were", "will be"],
    correctOption: 2,
    explanation: "In an imaginary (unreal) condition, formal English uses 'were' for all subjects: 'If I were you…'.",
    difficulty: "easy",
  },
  {
    id: "eng-ten-004",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: Kofi ___ to school every day.",
    options: ["go", "goes", "is going", "gone"],
    correctOption: 1,
    explanation: "Habitual actions use the simple present. With a singular third-person subject (Kofi), add -es: 'goes'.",
    difficulty: "easy",
  },
  {
    id: "eng-ten-005",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: They ___ football when it started to rain.",
    options: ["played", "were playing", "have played", "are playing"],
    correctOption: 1,
    explanation: "The past continuous ('were playing') describes an action in progress when another past action ('it started to rain') interrupted it.",
    difficulty: "medium",
  },
  {
    id: "eng-ten-006",
    topicId: "tenses",
    question: "Choose the option that best completes the sentence: If it rains tomorrow, we ___ the match.",
    options: ["would postpone", "will postpone", "postponed", "had postponed"],
    correctOption: 1,
    explanation: "A real, possible future condition uses the simple present in the if-clause and 'will' in the main clause.",
    difficulty: "medium",
  },

  // Synonyms
  {
    id: "eng-syn-001",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: The old man is known to be very FRUGAL.",
    options: ["wasteful", "thrifty", "generous", "careless"],
    correctOption: 1,
    explanation: "'Frugal' means careful not to waste money or resources. 'Thrifty' has the same meaning. 'Wasteful' is its opposite.",
    difficulty: "medium",
  },
  {
    id: "eng-syn-002",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: The instructions were AMBIGUOUS.",
    options: ["unclear", "obvious", "accurate", "final"],
    correctOption: 0,
    explanation: "'Ambiguous' means open to more than one interpretation, so it is unclear.",
    difficulty: "medium",
  },
  {
    id: "eng-syn-003",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: The teacher gave a LUCID explanation.",
    options: ["confusing", "lengthy", "clear", "brief"],
    correctOption: 2,
    explanation: "'Lucid' means easy to understand; clear.",
    difficulty: "medium",
  },
  {
    id: "eng-syn-004",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: The soldiers were ordered to ABANDON the camp.",
    options: ["defend", "leave", "clean", "build"],
    correctOption: 1,
    explanation: "To 'abandon' a place is to leave it, usually for good.",
    difficulty: "easy",
  },
  {
    id: "eng-syn-005",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: Ama is always COURTEOUS to visitors.",
    options: ["rude", "strange", "shy", "polite"],
    correctOption: 3,
    explanation: "'Courteous' means polite and respectful.",
    difficulty: "easy",
  },
  {
    id: "eng-syn-006",
    topicId: "synonyms",
    question: "Choose the word nearest in meaning to the word in capitals: The meeting has been POSTPONED.",
    options: ["cancelled", "put off", "brought forward", "held"],
    correctOption: 1,
    explanation: "To 'postpone' is to move an event to a later time, i.e. to put it off. A cancelled meeting will not happen at all.",
    difficulty: "easy",
  },

  // Antonyms
  {
    id: "eng-ant-001",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: Water is SCARCE in the dry season.",
    options: ["rare", "plentiful", "costly", "dirty"],
    correctOption: 1,
    explanation: "'Scarce' means in short supply. Its opposite is 'plentiful'. 'Rare' is a synonym, not an antonym.",
    difficulty: "easy",
  },
  {
    id: "eng-ant-002",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: His answer was VAGUE.",
    options: ["precise", "unclear", "long", "wrong"],
    correctOption: 0,
    explanation: "'Vague' means not clearly expressed. The opposite is 'precise'.",
    difficulty: "medium",
  },
  {
    id: "eng-ant-003",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: Yaw is a TIMID boy.",
    options: ["shy", "quiet", "bold", "weak"],
    correctOption: 2,
    explanation: "'Timid' means lacking courage or confidence. The opposite is 'bold'.",
    difficulty: "easy",
  },
  {
    id: "eng-ant-004",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: The water at this end of the pool is SHALLOW.",
    options: ["cold", "clear", "deep", "calm"],
    correctOption: 2,
    explanation: "'Shallow' means not deep, so its opposite is 'deep'.",
    difficulty: "easy",
  },
  {
    id: "eng-ant-005",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: The speaker sounded CONFIDENT.",
    options: ["certain", "unsure", "eloquent", "bold"],
    correctOption: 1,
    explanation: "'Confident' means sure of oneself. The opposite is 'unsure'.",
    difficulty: "easy",
  },
  {
    id: "eng-ant-006",
    topicId: "antonyms",
    question: "Choose the word opposite in meaning to the word in capitals: The witness gave an HONEST account.",
    options: ["frank", "truthful", "polite", "deceitful"],
    correctOption: 3,
    explanation: "'Honest' means truthful. Its opposite is 'deceitful'. 'Frank' and 'truthful' are synonyms.",
    difficulty: "easy",
  },

  // Prepositions
  {
    id: "eng-pre-001",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: Esi is very good ___ Mathematics.",
    options: ["in", "at", "on", "with"],
    correctOption: 1,
    explanation: "The fixed expression is 'good at' a subject or activity.",
    difficulty: "easy",
  },
  {
    id: "eng-pre-002",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: He was accused ___ stealing a phone.",
    options: ["for", "with", "of", "about"],
    correctOption: 2,
    explanation: "We say 'accused of' something. (Compare 'charged with' something.)",
    difficulty: "easy",
  },
  {
    id: "eng-pre-003",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: The students congratulated her ___ her success.",
    options: ["for", "on", "with", "about"],
    correctOption: 1,
    explanation: "The standard expression is 'congratulate someone on' something.",
    difficulty: "medium",
  },
  {
    id: "eng-pre-004",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: We have been waiting ___ two hours.",
    options: ["since", "for", "from", "by"],
    correctOption: 1,
    explanation: "Use 'for' with a length of time (two hours) and 'since' with a starting point (since 8 o'clock).",
    difficulty: "easy",
  },
  {
    id: "eng-pre-005",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: He insisted ___ paying for the meal.",
    options: ["in", "at", "for", "on"],
    correctOption: 3,
    explanation: "The verb 'insist' is followed by 'on': 'insisted on paying'.",
    difficulty: "easy",
  },
  {
    id: "eng-pre-006",
    topicId: "prepositions",
    question: "Choose the option that best completes the sentence: The bus arrived ___ the station at noon.",
    options: ["to", "at", "into", "on"],
    correctOption: 1,
    explanation: "We 'arrive at' a specific place such as a station, and 'arrive in' a city or country. We never 'arrive to' a place.",
    difficulty: "easy",
  },

  // Idioms
  {
    id: "eng-idi-001",
    topicId: "idioms",
    question: "What does the idiom 'to bury the hatchet' mean?",
    options: ["to hide a weapon", "to make peace", "to start a quarrel", "to dig a hole"],
    correctOption: 1,
    explanation: "'To bury the hatchet' means to end a quarrel and become friendly again.",
    difficulty: "easy",
  },
  {
    id: "eng-idi-002",
    topicId: "idioms",
    question: "Kwame burnt the midnight oil before his exams. This means he…",
    options: ["caused a fire at night", "studied late into the night", "slept very early", "wasted his time"],
    correctOption: 1,
    explanation: "'To burn the midnight oil' means to work or study late into the night.",
    difficulty: "easy",
  },
  {
    id: "eng-idi-003",
    topicId: "idioms",
    question: "The test was a piece of cake. This means the test was…",
    options: ["very easy", "very difficult", "very short", "unfair"],
    correctOption: 0,
    explanation: "'A piece of cake' describes something very easy to do.",
    difficulty: "easy",
  },
  {
    id: "eng-idi-004",
    topicId: "idioms",
    question: "What does 'to let the cat out of the bag' mean?",
    options: ["to set an animal free", "to reveal a secret", "to cause trouble", "to run away"],
    correctOption: 1,
    explanation: "'To let the cat out of the bag' means to reveal a secret, usually by accident.",
    difficulty: "easy",
  },
  {
    id: "eng-idi-005",
    topicId: "idioms",
    question: "When the teacher said the problem was poor time management, she hit the nail on the head. This means she…",
    options: ["was completely wrong", "described the problem exactly", "became angry", "punished the class"],
    correctOption: 1,
    explanation: "'To hit the nail on the head' means to describe exactly what is causing a situation or problem.",
    difficulty: "medium",
  },
  {
    id: "eng-idi-006",
    topicId: "idioms",
    question: "My uncle visits us once in a blue moon. This means he visits…",
    options: ["every month", "very rarely", "at night", "during festivals"],
    correctOption: 1,
    explanation: "'Once in a blue moon' means very rarely.",
    difficulty: "easy",
  },

  // Spelling
  {
    id: "eng-spe-001",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["accomodate", "acommodate", "accommodate", "accommadate"],
    correctOption: 2,
    explanation: "'Accommodate' has a double 'c' and a double 'm'.",
    difficulty: "medium",
  },
  {
    id: "eng-spe-002",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["neccessary", "necessary", "necesary", "neccesary"],
    correctOption: 1,
    explanation: "'Necessary' has one 'c' and a double 's'. A memory aid: one collar, two sleeves.",
    difficulty: "medium",
  },
  {
    id: "eng-spe-003",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["embarass", "embarras", "embarrass", "emmbarrass"],
    correctOption: 2,
    explanation: "'Embarrass' has a double 'r' and a double 's'.",
    difficulty: "medium",
  },
  {
    id: "eng-spe-004",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["occurence", "ocurrence", "occurrence", "occurance"],
    correctOption: 2,
    explanation: "'Occurrence' has a double 'c', a double 'r', and ends in '-ence'.",
    difficulty: "hard",
  },
  {
    id: "eng-spe-005",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["seperate", "separate", "separete", "seprate"],
    correctOption: 1,
    explanation: "'Separate' has 'a' after the 'p': sep-a-rate.",
    difficulty: "easy",
  },
  {
    id: "eng-spe-006",
    topicId: "spelling",
    question: "Choose the correctly spelt word.",
    options: ["definately", "definitly", "definitely", "defenitely"],
    correctOption: 2,
    explanation: "'Definitely' comes from 'definite', so it is spelt def-i-nite-ly.",
    difficulty: "easy",
  },
]);
