import { defineQuestions } from "./define";

export const integratedScienceQuestions = defineQuestions("integrated-science", [
  // Cells and Living Things
  {
    id: "sci-liv-001",
    topicId: "living-things",
    question: "Which cell organelle is the main site of aerobic respiration?",
    options: ["Nucleus", "Mitochondrion", "Ribosome", "Vacuole"],
    correctOption: 1,
    explanation: "Mitochondria release energy from food through aerobic respiration, which is why they are often called the 'powerhouse' of the cell.",
    difficulty: "easy",
  },
  {
    id: "sci-liv-002",
    topicId: "living-things",
    question: "Which of the following structures is found in plant cells but not in animal cells?",
    options: ["Nucleus", "Cell membrane", "Cell wall", "Mitochondrion"],
    correctOption: 2,
    explanation: "Plant cells have a cellulose cell wall outside the cell membrane. Animal cells have a cell membrane but no cell wall. Both have a nucleus and mitochondria.",
    difficulty: "easy",
  },
  {
    id: "sci-liv-003",
    topicId: "living-things",
    question: "The process by which green plants make their own food using light energy is called…",
    options: ["respiration", "transpiration", "photosynthesis", "germination"],
    correctOption: 2,
    explanation: "In photosynthesis, green plants use light energy, carbon dioxide and water to make glucose, releasing oxygen.",
    difficulty: "easy",
  },
  {
    id: "sci-liv-004",
    topicId: "living-things",
    question: "Which pigment in plants absorbs light energy for photosynthesis?",
    options: ["Haemoglobin", "Chlorophyll", "Melanin", "Keratin"],
    correctOption: 1,
    explanation: "Chlorophyll, found in chloroplasts, absorbs light energy and gives plants their green colour. Haemoglobin carries oxygen in human blood.",
    difficulty: "easy",
  },
  {
    id: "sci-liv-005",
    topicId: "living-things",
    question: "What is the basic structural and functional unit of all living things?",
    options: ["Tissue", "Organ", "Cell", "Atom"],
    correctOption: 2,
    explanation: "The cell is the basic unit of life. Cells form tissues, tissues form organs, and organs form systems.",
    difficulty: "easy",
  },
  {
    id: "sci-liv-006",
    topicId: "living-things",
    question: "Which of the following is NOT a characteristic of living things?",
    options: ["Respiration", "Reproduction", "Excretion", "Rusting"],
    correctOption: 3,
    explanation: "Rusting is a chemical change that happens to iron, a non-living thing. Respiration, reproduction and excretion are characteristics of living things.",
    difficulty: "easy",
  },

  // The Human Body
  {
    id: "sci-hum-001",
    topicId: "human-body",
    question: "Which organ pumps blood around the human body?",
    options: ["Lungs", "Liver", "Heart", "Kidney"],
    correctOption: 2,
    explanation: "The heart is a muscular organ that pumps blood through the blood vessels to all parts of the body.",
    difficulty: "easy",
  },
  {
    id: "sci-hum-002",
    topicId: "human-body",
    question: "Which blood cells help the body fight infection?",
    options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"],
    correctOption: 1,
    explanation: "White blood cells defend the body against germs. Red blood cells carry oxygen, and platelets help blood to clot.",
    difficulty: "easy",
  },
  {
    id: "sci-hum-003",
    topicId: "human-body",
    question: "Where does the digestion of starch begin?",
    options: ["Mouth", "Stomach", "Small intestine", "Large intestine"],
    correctOption: 0,
    explanation: "Saliva in the mouth contains the enzyme salivary amylase, which begins breaking starch down into sugars.",
    difficulty: "medium",
  },
  {
    id: "sci-hum-004",
    topicId: "human-body",
    question: "In which structures of the lungs does gaseous exchange take place?",
    options: ["Trachea", "Bronchi", "Alveoli", "Diaphragm"],
    correctOption: 2,
    explanation: "Alveoli are tiny air sacs with thin walls and a rich blood supply, where oxygen enters the blood and carbon dioxide leaves it.",
    difficulty: "medium",
  },
  {
    id: "sci-hum-005",
    topicId: "human-body",
    question: "Which organ filters the blood to produce urine?",
    options: ["Liver", "Kidney", "Bladder", "Pancreas"],
    correctOption: 1,
    explanation: "The kidneys filter waste such as urea from the blood to form urine. The bladder only stores urine.",
    difficulty: "easy",
  },
  {
    id: "sci-hum-006",
    topicId: "human-body",
    question: "Scurvy is caused by a lack of which vitamin?",
    options: ["Vitamin A", "Vitamin B1", "Vitamin C", "Vitamin D"],
    correctOption: 2,
    explanation: "Lack of vitamin C causes scurvy, with symptoms such as bleeding gums. Citrus fruits like oranges are good sources of vitamin C.",
    difficulty: "easy",
  },
  {
    id: "sci-hum-007",
    topicId: "human-body",
    question: "Malaria is transmitted to humans by the bite of…",
    options: ["the housefly", "the female Anopheles mosquito", "the tsetse fly", "the male Anopheles mosquito"],
    correctOption: 1,
    explanation: "The malaria parasite (Plasmodium) is passed to humans by infected female Anopheles mosquitoes. Only females feed on blood.",
    difficulty: "easy",
  },

  // Matter
  {
    id: "sci-mat-001",
    topicId: "matter",
    question: "The change of a substance directly from the solid state to the gaseous state is called…",
    options: ["evaporation", "condensation", "sublimation", "melting"],
    correctOption: 2,
    explanation: "Sublimation is the change from solid directly to gas without becoming a liquid, as happens with iodine crystals or dry ice.",
    difficulty: "easy",
  },
  {
    id: "sci-mat-002",
    topicId: "matter",
    question: "Which of the following is a compound?",
    options: ["Oxygen", "Iron", "Water", "Air"],
    correctOption: 2,
    explanation: "Water (H₂O) is a compound of hydrogen and oxygen chemically combined. Oxygen and iron are elements, and air is a mixture.",
    difficulty: "easy",
  },
  {
    id: "sci-mat-003",
    topicId: "matter",
    question: "What is the pH of a neutral solution such as pure water at 25 °C?",
    options: ["0", "5", "7", "14"],
    correctOption: 2,
    explanation: "On the pH scale, 7 is neutral. Values below 7 are acidic and values above 7 are alkaline.",
    difficulty: "easy",
  },
  {
    id: "sci-mat-004",
    topicId: "matter",
    question: "Which of the following is a physical change?",
    options: ["Melting of ice", "Burning of paper", "Rusting of iron", "Cooking an egg"],
    correctOption: 0,
    explanation: "Melting ice changes only its state; no new substance is formed and it can be reversed by freezing. The others form new substances, so they are chemical changes.",
    difficulty: "easy",
  },
  {
    id: "sci-mat-005",
    topicId: "matter",
    question: "Which particle in an atom carries a negative charge?",
    options: ["Proton", "Neutron", "Electron", "Nucleus"],
    correctOption: 2,
    explanation: "Electrons are negatively charged, protons are positively charged and neutrons have no charge.",
    difficulty: "easy",
  },
  {
    id: "sci-mat-006",
    topicId: "matter",
    question: "Which method can be used to obtain common salt from a salt solution?",
    options: ["Filtration", "Evaporation", "Decantation", "Sieving"],
    correctOption: 1,
    explanation: "Heating the solution evaporates the water and leaves the dissolved salt behind. Filtration cannot separate a dissolved solid.",
    difficulty: "easy",
  },

  // Energy
  {
    id: "sci-ene-001",
    topicId: "energy",
    question: "What is the SI unit of energy?",
    options: ["Watt", "Newton", "Joule", "Volt"],
    correctOption: 2,
    explanation: "Energy is measured in joules (J). The watt is the unit of power, the newton of force and the volt of potential difference.",
    difficulty: "easy",
  },
  {
    id: "sci-ene-002",
    topicId: "energy",
    question: "A dry cell (battery) converts…",
    options: ["electrical energy to chemical energy", "chemical energy to electrical energy", "light energy to electrical energy", "heat energy to chemical energy"],
    correctOption: 1,
    explanation: "Chemical reactions inside a dry cell produce electrical energy. A solar panel converts light energy to electrical energy.",
    difficulty: "easy",
  },
  {
    id: "sci-ene-003",
    topicId: "energy",
    question: "Which of the following is a renewable source of energy?",
    options: ["Coal", "Crude oil", "Solar energy", "Natural gas"],
    correctOption: 2,
    explanation: "Solar energy is naturally replenished. Coal, crude oil and natural gas are fossil fuels that take millions of years to form.",
    difficulty: "easy",
  },
  {
    id: "sci-ene-004",
    topicId: "energy",
    question: "By which method is heat transferred through a vacuum, such as from the Sun to the Earth?",
    options: ["Conduction", "Convection", "Radiation", "Evaporation"],
    correctOption: 2,
    explanation: "Radiation does not need a medium, so it can travel through a vacuum. Conduction and convection need particles of matter.",
    difficulty: "easy",
  },
  {
    id: "sci-ene-005",
    topicId: "energy",
    question: "The energy possessed by a body because of its motion is called…",
    options: ["potential energy", "kinetic energy", "chemical energy", "nuclear energy"],
    correctOption: 1,
    explanation: "Kinetic energy is energy of motion. Potential energy is stored energy due to position or condition.",
    difficulty: "easy",
  },
  {
    id: "sci-ene-006",
    topicId: "energy",
    question: "The Akosombo Dam in Ghana generates electricity mainly from…",
    options: ["solar energy", "wind energy", "flowing water (hydroelectric power)", "burning coal"],
    correctOption: 2,
    explanation: "Akosombo is a hydroelectric dam on the Volta River. The kinetic energy of flowing water turns turbines connected to generators.",
    difficulty: "easy",
  },

  // Ecosystems
  {
    id: "sci-eco-001",
    topicId: "ecosystems",
    question: "Organisms that make their own food are called…",
    options: ["consumers", "producers", "decomposers", "parasites"],
    correctOption: 1,
    explanation: "Producers, mainly green plants, make their own food by photosynthesis. All other organisms in a food chain depend on them.",
    difficulty: "easy",
  },
  {
    id: "sci-eco-002",
    topicId: "ecosystems",
    question: "In the food chain grass → grasshopper → frog → snake, which organism is the primary consumer?",
    options: ["Grass", "Grasshopper", "Frog", "Snake"],
    correctOption: 1,
    explanation: "The primary consumer feeds directly on the producer. The grasshopper eats grass, so it is the primary consumer.",
    difficulty: "easy",
  },
  {
    id: "sci-eco-003",
    topicId: "ecosystems",
    question: "Which organisms break down dead plants and animals and return nutrients to the soil?",
    options: ["Producers", "Herbivores", "Decomposers", "Carnivores"],
    correctOption: 2,
    explanation: "Decomposers such as bacteria and fungi break down dead matter, recycling nutrients back into the soil.",
    difficulty: "easy",
  },
  {
    id: "sci-eco-004",
    topicId: "ecosystems",
    question: "A relationship between two organisms in which both benefit is called…",
    options: ["parasitism", "mutualism", "predation", "competition"],
    correctOption: 1,
    explanation: "In mutualism both organisms benefit, for example legumes and nitrogen-fixing bacteria. In parasitism, one benefits and the other is harmed.",
    difficulty: "medium",
  },
  {
    id: "sci-eco-005",
    topicId: "ecosystems",
    question: "Which gas is released by green plants during photosynthesis?",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    correctOption: 2,
    explanation: "Photosynthesis takes in carbon dioxide and releases oxygen as a by-product.",
    difficulty: "easy",
  },
  {
    id: "sci-eco-006",
    topicId: "ecosystems",
    question: "Nitrogen-fixing bacteria are commonly found in the root nodules of…",
    options: ["cassava", "maize", "legumes such as groundnut and cowpea", "yam"],
    correctOption: 2,
    explanation: "Legumes have root nodules containing bacteria that convert atmospheric nitrogen into compounds plants can use, which improves soil fertility.",
    difficulty: "medium",
  },

  // Forces and Motion
  {
    id: "sci-for-001",
    topicId: "forces",
    question: "What is the SI unit of force?",
    options: ["Joule", "Newton", "Kilogram", "Pascal"],
    correctOption: 1,
    explanation: "Force is measured in newtons (N). The kilogram is the unit of mass and the pascal is the unit of pressure.",
    difficulty: "easy",
  },
  {
    id: "sci-for-002",
    topicId: "forces",
    question: "A car travels 120 km in 2 hours. What is its average speed?",
    options: ["30 km/h", "60 km/h", "122 km/h", "240 km/h"],
    correctOption: 1,
    explanation: "Average speed = distance ÷ time = 120 km ÷ 2 h = 60 km/h.",
    difficulty: "easy",
  },
  {
    id: "sci-for-003",
    topicId: "forces",
    question: "The force that opposes motion between two surfaces in contact is called…",
    options: ["gravity", "friction", "tension", "magnetism"],
    correctOption: 1,
    explanation: "Friction acts between surfaces in contact and opposes their relative motion.",
    difficulty: "easy",
  },
  {
    id: "sci-for-004",
    topicId: "forces",
    question: "Find the weight of an object of mass 5 kg. [Take g = 10 m/s²]",
    options: ["0.5 N", "5 N", "15 N", "50 N"],
    correctOption: 3,
    explanation: "Weight = mass × acceleration due to gravity = 5 kg × 10 m/s² = 50 N.",
    difficulty: "easy",
  },
  {
    id: "sci-for-005",
    topicId: "forces",
    question: "A crowbar used to lift a heavy stone is an example of which simple machine?",
    options: ["Pulley", "Lever", "Inclined plane", "Screw"],
    correctOption: 1,
    explanation: "A lever is a rigid bar that turns about a pivot (fulcrum). A crowbar lets a small effort lift a large load. Scissors and bottle openers are also levers.",
    difficulty: "easy",
  },
  {
    id: "sci-for-006",
    topicId: "forces",
    question: "Which statement about mass and weight is correct?",
    options: [
      "Mass is measured in newtons",
      "Weight is the amount of matter in a body",
      "Mass stays the same everywhere, but weight can change",
      "Mass and weight are the same thing",
    ],
    correctOption: 2,
    explanation: "Mass (kg) is the amount of matter and does not change with location. Weight (N) is the pull of gravity on that mass, so it changes, for example on the Moon.",
    difficulty: "medium",
  },
]);
