import { defineQuestions } from "./define";

export const mathematicsQuestions = defineQuestions("mathematics", [
  // Number and Numeration
  {
    id: "math-num-001",
    topicId: "number",
    question: "Express 0.000356 in standard form.",
    options: ["3.56 × 10⁻⁴", "3.56 × 10⁻³", "35.6 × 10⁻⁵", "3.56 × 10⁴"],
    correctOption: 0,
    explanation: "Standard form is A × 10ⁿ with 1 ≤ A < 10. Move the decimal point 4 places to the right to get 3.56, so n = −4: 0.000356 = 3.56 × 10⁻⁴.",
    difficulty: "easy",
  },
  {
    id: "math-num-002",
    topicId: "number",
    question: "Convert 1011₂ to a base ten number.",
    options: ["9", "11", "12", "13"],
    correctOption: 1,
    explanation: "1011₂ = (1 × 2³) + (0 × 2²) + (1 × 2¹) + (1 × 2⁰) = 8 + 0 + 2 + 1 = 11.",
    difficulty: "easy",
  },
  {
    id: "math-num-003",
    topicId: "number",
    question: "Simplify 2¾ − 1⅚.",
    options: ["5/12", "7/12", "11/12", "1 1/12"],
    correctOption: 2,
    explanation: "Convert to improper fractions: 11/4 − 11/6. Using the LCM 12: 33/12 − 22/12 = 11/12.",
    difficulty: "medium",
  },
  {
    id: "math-num-004",
    topicId: "number",
    question: "Find the HCF of 36 and 60.",
    options: ["6", "12", "18", "180"],
    correctOption: 1,
    explanation: "36 = 2² × 3² and 60 = 2² × 3 × 5. The HCF uses the lowest power of each common prime: 2² × 3 = 12. (180 is the LCM.)",
    difficulty: "easy",
  },
  {
    id: "math-num-005",
    topicId: "number",
    question: "Evaluate log₁₀ 1000 + log₁₀ 0.01.",
    options: ["−1", "0", "1", "5"],
    correctOption: 2,
    explanation: "1000 = 10³, so log₁₀ 1000 = 3. 0.01 = 10⁻², so log₁₀ 0.01 = −2. 3 + (−2) = 1.",
    difficulty: "medium",
  },
  {
    id: "math-num-006",
    topicId: "number",
    question: "A trader buys an item for GH₵80 and sells it for GH₵100. What is the profit as a percentage of the cost price?",
    options: ["20%", "25%", "80%", "125%"],
    correctOption: 1,
    explanation: "Profit = 100 − 80 = GH₵20. Profit % = (profit ÷ cost price) × 100 = (20 ÷ 80) × 100 = 25%.",
    difficulty: "easy",
  },
  {
    id: "math-num-007",
    topicId: "number",
    question: "Evaluate 8^(2/3).",
    options: ["2", "4", "16/3", "16"],
    correctOption: 1,
    explanation: "8^(2/3) = (∛8)² = 2² = 4. The denominator of the index is the root; the numerator is the power.",
    difficulty: "medium",
  },

  // Algebra
  {
    id: "math-alg-001",
    topicId: "algebra",
    question: "Solve 3x − 7 = 11.",
    options: ["x = 4/3", "x = 3", "x = 6", "x = 18"],
    correctOption: 2,
    explanation: "Add 7 to both sides: 3x = 18. Divide both sides by 3: x = 6.",
    difficulty: "easy",
  },
  {
    id: "math-alg-002",
    topicId: "algebra",
    question: "Factorise x² − 5x + 6.",
    options: ["(x + 2)(x + 3)", "(x − 2)(x − 3)", "(x − 1)(x − 6)", "(x + 1)(x − 6)"],
    correctOption: 1,
    explanation: "Find two numbers that multiply to +6 and add to −5: −2 and −3. So x² − 5x + 6 = (x − 2)(x − 3).",
    difficulty: "easy",
  },
  {
    id: "math-alg-003",
    topicId: "algebra",
    question: "If f(x) = 2x² − 3, find f(−2).",
    options: ["−11", "−5", "5", "11"],
    correctOption: 2,
    explanation: "f(−2) = 2(−2)² − 3 = 2(4) − 3 = 8 − 3 = 5. Remember (−2)² = +4.",
    difficulty: "easy",
  },
  {
    id: "math-alg-004",
    topicId: "algebra",
    question: "Solve the simultaneous equations x + y = 7 and x − y = 1.",
    options: ["x = 3, y = 4", "x = 4, y = 3", "x = 5, y = 2", "x = 6, y = 1"],
    correctOption: 1,
    explanation: "Adding the equations gives 2x = 8, so x = 4. Substituting into x + y = 7 gives y = 3.",
    difficulty: "easy",
  },
  {
    id: "math-alg-005",
    topicId: "algebra",
    question: "Make r the subject of the formula A = πr².",
    options: ["r = A/π", "r = √(Aπ)", "r = √(A/π)", "r = (A/π)²"],
    correctOption: 2,
    explanation: "Divide both sides by π: r² = A/π. Take the square root of both sides: r = √(A/π).",
    difficulty: "medium",
  },
  {
    id: "math-alg-006",
    topicId: "algebra",
    question: "Find the roots of the equation x² − 9 = 0.",
    options: ["x = 3 only", "x = ±3", "x = 9", "x = ±9"],
    correctOption: 1,
    explanation: "x² − 9 = (x − 3)(x + 3) = 0, so x = 3 or x = −3. A quadratic equation can have two roots.",
    difficulty: "easy",
  },
  {
    id: "math-alg-007",
    topicId: "algebra",
    question: "Simplify (2a³b)(3ab²).",
    options: ["5a⁴b³", "6a³b²", "6a⁴b³", "6a⁴b²"],
    correctOption: 2,
    explanation: "Multiply the numbers: 2 × 3 = 6. Add the indices of like letters: a³ × a = a⁴ and b × b² = b³. Result: 6a⁴b³.",
    difficulty: "easy",
  },

  // Geometry
  {
    id: "math-geo-001",
    topicId: "geometry",
    question: "What is the sum of the interior angles of a hexagon?",
    options: ["360°", "540°", "720°", "900°"],
    correctOption: 2,
    explanation: "Sum of interior angles = (n − 2) × 180°. For a hexagon n = 6: (6 − 2) × 180° = 720°.",
    difficulty: "easy",
  },
  {
    id: "math-geo-002",
    topicId: "geometry",
    question: "Each exterior angle of a regular polygon is 40°. How many sides does the polygon have?",
    options: ["6", "8", "9", "10"],
    correctOption: 2,
    explanation: "The exterior angles of any polygon add up to 360°. Number of sides = 360° ÷ 40° = 9.",
    difficulty: "medium",
  },
  {
    id: "math-geo-003",
    topicId: "geometry",
    question: "Two angles of a triangle are 65° and 45°. Find the third angle.",
    options: ["60°", "70°", "80°", "110°"],
    correctOption: 1,
    explanation: "Angles in a triangle add up to 180°. Third angle = 180° − (65° + 45°) = 70°.",
    difficulty: "easy",
  },
  {
    id: "math-geo-004",
    topicId: "geometry",
    question: "What is the size of the angle in a semicircle?",
    options: ["45°", "90°", "180°", "360°"],
    correctOption: 1,
    explanation: "An angle subtended by a diameter at any point on the circumference is a right angle (90°).",
    difficulty: "easy",
  },
  {
    id: "math-geo-005",
    topicId: "geometry",
    question: "The two shorter sides of a right-angled triangle are 6 cm and 8 cm. Find the length of the hypotenuse.",
    options: ["10 cm", "12 cm", "14 cm", "48 cm"],
    correctOption: 0,
    explanation: "By Pythagoras' theorem, c² = 6² + 8² = 36 + 64 = 100, so c = √100 = 10 cm.",
    difficulty: "easy",
  },
  {
    id: "math-geo-006",
    topicId: "geometry",
    question: "Two angles are supplementary. One of them is 112°. Find the other.",
    options: ["22°", "68°", "78°", "248°"],
    correctOption: 1,
    explanation: "Supplementary angles add up to 180°. 180° − 112° = 68°. (Complementary angles add up to 90°.)",
    difficulty: "easy",
  },

  // Mensuration
  {
    id: "math-men-001",
    topicId: "mensuration",
    question: "Find the area of a circle of radius 7 cm. [Take π = 22/7]",
    options: ["44 cm²", "49 cm²", "154 cm²", "308 cm²"],
    correctOption: 2,
    explanation: "Area = πr² = 22/7 × 7 × 7 = 22 × 7 = 154 cm². (44 cm is the circumference.)",
    difficulty: "easy",
  },
  {
    id: "math-men-002",
    topicId: "mensuration",
    question: "Find the circumference of a circle of diameter 14 cm. [Take π = 22/7]",
    options: ["22 cm", "44 cm", "88 cm", "154 cm"],
    correctOption: 1,
    explanation: "Circumference = πd = 22/7 × 14 = 44 cm.",
    difficulty: "easy",
  },
  {
    id: "math-men-003",
    topicId: "mensuration",
    question: "A cuboid measures 5 cm by 4 cm by 3 cm. Find its volume.",
    options: ["12 cm³", "47 cm³", "60 cm³", "94 cm³"],
    correctOption: 2,
    explanation: "Volume of a cuboid = length × width × height = 5 × 4 × 3 = 60 cm³.",
    difficulty: "easy",
  },
  {
    id: "math-men-004",
    topicId: "mensuration",
    question: "Find the area of a triangle with base 10 cm and height 6 cm.",
    options: ["16 cm²", "30 cm²", "60 cm²", "32 cm²"],
    correctOption: 1,
    explanation: "Area of a triangle = ½ × base × height = ½ × 10 × 6 = 30 cm².",
    difficulty: "easy",
  },
  {
    id: "math-men-005",
    topicId: "mensuration",
    question: "Find the volume of a cylinder of radius 7 cm and height 10 cm. [Take π = 22/7]",
    options: ["440 cm³", "770 cm³", "1540 cm³", "3080 cm³"],
    correctOption: 2,
    explanation: "Volume = πr²h = 22/7 × 7 × 7 × 10 = 154 × 10 = 1540 cm³.",
    difficulty: "medium",
  },
  {
    id: "math-men-006",
    topicId: "mensuration",
    question: "Find the total surface area of a cube of side 3 cm.",
    options: ["9 cm²", "27 cm²", "36 cm²", "54 cm²"],
    correctOption: 3,
    explanation: "A cube has 6 equal square faces. Total surface area = 6 × 3² = 6 × 9 = 54 cm². (27 cm³ is its volume.)",
    difficulty: "easy",
  },

  // Statistics
  {
    id: "math-sta-001",
    topicId: "statistics",
    question: "Find the mean of 4, 7, 9, 10 and 15.",
    options: ["7", "9", "10", "11"],
    correctOption: 1,
    explanation: "Mean = sum ÷ number of values = (4 + 7 + 9 + 10 + 15) ÷ 5 = 45 ÷ 5 = 9.",
    difficulty: "easy",
  },
  {
    id: "math-sta-002",
    topicId: "statistics",
    question: "Find the median of 3, 8, 5, 12 and 7.",
    options: ["5", "7", "8", "12"],
    correctOption: 1,
    explanation: "Arrange in order: 3, 5, 7, 8, 12. The middle value is 7. Always sort the data before finding the median.",
    difficulty: "easy",
  },
  {
    id: "math-sta-003",
    topicId: "statistics",
    question: "Find the mode of 2, 4, 4, 5, 6, 4, 7, 5.",
    options: ["4", "5", "4.5", "7"],
    correctOption: 0,
    explanation: "The mode is the value that occurs most often. 4 appears three times, more than any other value.",
    difficulty: "easy",
  },
  {
    id: "math-sta-004",
    topicId: "statistics",
    question: "Find the range of 12, 5, 19, 8 and 10.",
    options: ["7", "10", "14", "19"],
    correctOption: 2,
    explanation: "Range = highest value − lowest value = 19 − 5 = 14.",
    difficulty: "easy",
  },
  {
    id: "math-sta-005",
    topicId: "statistics",
    question: "In a school of 120 students, 30 walk to school. What angle represents this group on a pie chart?",
    options: ["30°", "45°", "90°", "120°"],
    correctOption: 2,
    explanation: "Angle = (30 ÷ 120) × 360° = ¼ × 360° = 90°.",
    difficulty: "medium",
  },
  {
    id: "math-sta-006",
    topicId: "statistics",
    question: "Find the median of 4, 9, 2, 7, 5 and 10.",
    options: ["5", "6", "6.2", "7"],
    correctOption: 1,
    explanation: "Sorted: 2, 4, 5, 7, 9, 10. With an even number of values, the median is the mean of the two middle values: (5 + 7) ÷ 2 = 6.",
    difficulty: "medium",
  },

  // Probability
  {
    id: "math-pro-001",
    topicId: "probability",
    question: "A fair die is thrown once. What is the probability of getting an even number?",
    options: ["1/6", "1/3", "1/2", "2/3"],
    correctOption: 2,
    explanation: "The even numbers are 2, 4 and 6: 3 favourable outcomes out of 6. P(even) = 3/6 = 1/2.",
    difficulty: "easy",
  },
  {
    id: "math-pro-002",
    topicId: "probability",
    question: "A bag contains 5 red balls and 3 blue balls. A ball is picked at random. What is the probability that it is blue?",
    options: ["3/5", "3/8", "5/8", "1/3"],
    correctOption: 1,
    explanation: "There are 5 + 3 = 8 balls in total and 3 are blue. P(blue) = 3/8.",
    difficulty: "easy",
  },
  {
    id: "math-pro-003",
    topicId: "probability",
    question: "Two fair coins are tossed together. What is the probability of getting two heads?",
    options: ["1/4", "1/3", "1/2", "3/4"],
    correctOption: 0,
    explanation: "Possible outcomes: HH, HT, TH, TT. Only HH is two heads, so P = 1/4. Equivalently, ½ × ½ = ¼.",
    difficulty: "medium",
  },
  {
    id: "math-pro-004",
    topicId: "probability",
    question: "The probability that an event happens is 0.35. What is the probability that it does not happen?",
    options: ["0.35", "0.55", "0.65", "1.35"],
    correctOption: 2,
    explanation: "P(not A) = 1 − P(A) = 1 − 0.35 = 0.65.",
    difficulty: "easy",
  },
  {
    id: "math-pro-005",
    topicId: "probability",
    question: "A card is drawn at random from a standard pack of 52 playing cards. What is the probability that it is a king?",
    options: ["1/52", "1/13", "1/4", "4/13"],
    correctOption: 1,
    explanation: "There are 4 kings in 52 cards. P(king) = 4/52 = 1/13.",
    difficulty: "easy",
  },
  {
    id: "math-pro-006",
    topicId: "probability",
    question: "A fair die is thrown once. What is the probability of getting a number greater than 4?",
    options: ["1/6", "1/3", "1/2", "2/3"],
    correctOption: 1,
    explanation: "Numbers greater than 4 are 5 and 6: 2 outcomes out of 6. P = 2/6 = 1/3.",
    difficulty: "easy",
  },

  // Trigonometry
  {
    id: "math-tri-001",
    topicId: "trigonometry",
    question: "What is the value of sin 30°?",
    options: ["1/2", "√3/2", "1/√2", "1"],
    correctOption: 0,
    explanation: "sin 30° = 1/2 is a special-angle value worth memorising, along with cos 60° = 1/2.",
    difficulty: "easy",
  },
  {
    id: "math-tri-002",
    topicId: "trigonometry",
    question: "In a right-angled triangle, the side opposite angle θ is 3 cm and the hypotenuse is 5 cm. Find cos θ.",
    options: ["3/5", "4/5", "3/4", "5/4"],
    correctOption: 1,
    explanation: "By Pythagoras, the adjacent side = √(5² − 3²) = √16 = 4 cm. cos θ = adjacent ÷ hypotenuse = 4/5.",
    difficulty: "medium",
  },
  {
    id: "math-tri-003",
    topicId: "trigonometry",
    question: "What is the value of tan 45°?",
    options: ["0", "1/2", "1", "√3"],
    correctOption: 2,
    explanation: "In a right-angled isosceles triangle, the opposite and adjacent sides are equal, so tan 45° = 1.",
    difficulty: "easy",
  },
  {
    id: "math-tri-004",
    topicId: "trigonometry",
    question: "If sin θ = cos θ and θ is an acute angle, find θ.",
    options: ["30°", "45°", "60°", "90°"],
    correctOption: 1,
    explanation: "sin θ = cos θ means tan θ = sin θ ÷ cos θ = 1, so θ = 45°.",
    difficulty: "medium",
  },
  {
    id: "math-tri-005",
    topicId: "trigonometry",
    question: "A ladder 10 m long leans against a vertical wall and makes an angle of 60° with the horizontal ground. How high up the wall does the ladder reach?",
    options: ["5 m", "5√3 m", "10√3 m", "20 m"],
    correctOption: 1,
    explanation: "Height = 10 × sin 60° = 10 × √3/2 = 5√3 m (about 8.66 m).",
    difficulty: "hard",
  },
  {
    id: "math-tri-006",
    topicId: "trigonometry",
    question: "What is the value of cos 60°?",
    options: ["0", "1/2", "√3/2", "1"],
    correctOption: 1,
    explanation: "cos 60° = 1/2. Notice cos 60° = sin 30° because 30° and 60° are complementary.",
    difficulty: "easy",
  },
]);
