import { defineQuestions } from "./define";

export const socialStudiesQuestions = defineQuestions("social-studies", [
  // Our Environment
  {
    id: "soc-env-001",
    topicId: "environment",
    question: "Which of the following is a major effect of deforestation?",
    options: ["Increased soil fertility", "Soil erosion", "More rainfall", "Cooler temperatures"],
    correctOption: 1,
    explanation: "Tree roots hold soil together and leaves protect it from heavy rain. When forests are cleared, rain and wind wash away the topsoil, causing erosion.",
    difficulty: "easy",
  },
  {
    id: "soc-env-002",
    topicId: "environment",
    question: "Illegal small-scale mining in Ghana is commonly referred to as…",
    options: ["galamsey", "kayayei", "susu", "okada"],
    correctOption: 0,
    explanation: "'Galamsey' refers to illegal small-scale mining, which pollutes rivers, destroys farmland and degrades forests.",
    difficulty: "easy",
  },
  {
    id: "soc-env-003",
    topicId: "environment",
    question: "Which of the following is part of the physical environment?",
    options: ["Schools", "Markets", "Rivers", "Festivals"],
    correctOption: 2,
    explanation: "The physical environment is made up of natural features such as rivers, relief, climate, soils and vegetation. Schools, markets and festivals belong to the social environment.",
    difficulty: "easy",
  },
  {
    id: "soc-env-004",
    topicId: "environment",
    question: "Which practice helps to conserve forests?",
    options: ["Bush burning", "Reforestation", "Overgrazing", "Illegal chainsaw logging"],
    correctOption: 1,
    explanation: "Reforestation means planting trees to replace those that have been cut down. The other practices destroy vegetation.",
    difficulty: "easy",
  },
  {
    id: "soc-env-005",
    topicId: "environment",
    question: "Which of the following is a human cause of flooding in many towns and cities?",
    options: [
      "Blocked drains caused by improper refuse disposal",
      "The rotation of the Earth",
      "The dry harmattan winds",
      "High daytime temperatures",
    ],
    correctOption: 0,
    explanation: "When refuse is dumped into gutters and drains, rainwater cannot flow away, so streets flood. Proper waste disposal reduces this risk.",
    difficulty: "easy",
  },

  // Governance and the Constitution
  {
    id: "soc-gov-001",
    topicId: "governance",
    question: "The three arms of government are…",
    options: [
      "the Executive, the Legislature and the Judiciary",
      "the President, the Police and the Army",
      "Parliament, the Chiefs and the Courts",
      "the Ministries, the Assemblies and the Unit Committees",
    ],
    correctOption: 0,
    explanation: "The Executive implements laws, the Legislature (Parliament) makes laws, and the Judiciary interprets laws and settles disputes.",
    difficulty: "easy",
  },
  {
    id: "soc-gov-002",
    topicId: "governance",
    question: "Which arm of government is responsible for making laws?",
    options: ["The Executive", "The Legislature", "The Judiciary", "The Police Service"],
    correctOption: 1,
    explanation: "The Legislature makes laws. In Ghana, this is Parliament.",
    difficulty: "easy",
  },
  {
    id: "soc-gov-003",
    topicId: "governance",
    question: "In which year did Ghana's Fourth Republican Constitution get approved by a national referendum?",
    options: ["1957", "1960", "1979", "1992"],
    correctOption: 3,
    explanation: "The 1992 Constitution was approved by referendum in April 1992 and came into force on 7 January 1993, starting the Fourth Republic.",
    difficulty: "medium",
  },
  {
    id: "soc-gov-004",
    topicId: "governance",
    question: "The 'rule of law' means that…",
    options: [
      "only the President can make laws",
      "everyone, including leaders, is subject to the law and equal before it",
      "the police can arrest anyone at any time",
      "laws apply only to ordinary citizens",
    ],
    correctOption: 1,
    explanation: "Under the rule of law, no one is above the law, everyone is equal before it, and people are punished only for breaking established laws.",
    difficulty: "easy",
  },
  {
    id: "soc-gov-005",
    topicId: "governance",
    question: "The main purpose of the separation of powers is to…",
    options: [
      "make government work faster",
      "prevent the abuse of power by any one arm of government",
      "give the President more authority",
      "reduce the number of government workers",
    ],
    correctOption: 1,
    explanation: "Dividing power among the Executive, Legislature and Judiciary, with checks and balances, stops any one arm from becoming too powerful.",
    difficulty: "medium",
  },
  {
    id: "soc-gov-006",
    topicId: "governance",
    question: "On which date did Ghana gain independence?",
    options: ["1st July 1960", "6th March 1957", "24th February 1966", "7th January 1993"],
    correctOption: 1,
    explanation: "Ghana gained independence from Britain on 6th March 1957. It became a republic on 1st July 1960.",
    difficulty: "easy",
  },
  {
    id: "soc-gov-007",
    topicId: "governance",
    question: "How many administrative regions does Ghana currently have?",
    options: ["10", "12", "16", "18"],
    correctOption: 2,
    explanation: "Ghana has 16 regions. Six new regions were created in 2019 following referendums, increasing the number from 10.",
    difficulty: "easy",
  },

  // Socialisation and the Family
  {
    id: "soc-soc-001",
    topicId: "socialisation",
    question: "Which is the primary (first) agent of socialisation?",
    options: ["The school", "The family", "The mass media", "The peer group"],
    correctOption: 1,
    explanation: "The family is the first place a child learns language, values, norms and behaviour, so it is the primary agent of socialisation.",
    difficulty: "easy",
  },
  {
    id: "soc-soc-002",
    topicId: "socialisation",
    question: "Socialisation can best be described as the process by which…",
    options: [
      "people form political parties",
      "individuals learn the values, norms and behaviour of their society",
      "a country becomes developed",
      "people move from rural to urban areas",
    ],
    correctOption: 1,
    explanation: "Socialisation is the lifelong process of learning the values, norms, beliefs and skills needed to live in a society.",
    difficulty: "easy",
  },
  {
    id: "soc-soc-003",
    topicId: "socialisation",
    question: "A nuclear family is made up of…",
    options: [
      "a father, a mother and their children",
      "parents, children, grandparents, uncles and aunts",
      "all members of a clan",
      "friends who live together",
    ],
    correctOption: 0,
    explanation: "A nuclear family consists of parents and their children. When other relatives are included, it is an extended family.",
    difficulty: "easy",
  },
  {
    id: "soc-soc-004",
    topicId: "socialisation",
    question: "A group of people of about the same age, interests or social status is called a…",
    options: ["clan", "peer group", "lineage", "committee"],
    correctOption: 1,
    explanation: "A peer group is made up of people of similar age or status. Peer groups strongly influence behaviour, especially during adolescence.",
    difficulty: "easy",
  },
  {
    id: "soc-soc-005",
    topicId: "socialisation",
    question: "Which of the following is a member of the extended family but not the nuclear family?",
    options: ["Father", "Mother", "Son", "Grandmother"],
    correctOption: 3,
    explanation: "The extended family includes relatives beyond parents and children, such as grandparents, uncles, aunts and cousins.",
    difficulty: "easy",
  },

  // Citizenship and Rights
  {
    id: "soc-cit-001",
    topicId: "citizenship",
    question: "Which of the following is a responsibility of a citizen?",
    options: ["Paying taxes", "Receiving free healthcare", "Owning property", "Travelling abroad"],
    correctOption: 0,
    explanation: "Paying taxes is a civic responsibility that helps government provide services such as schools, roads and hospitals. The others are rights or privileges.",
    difficulty: "easy",
  },
  {
    id: "soc-cit-002",
    topicId: "citizenship",
    question: "Under Ghana's 1992 Constitution, a citizen qualifies to vote from what age?",
    options: ["16 years", "18 years", "21 years", "25 years"],
    correctOption: 1,
    explanation: "Every citizen of Ghana who is 18 years or older and of sound mind has the right to vote (Article 42 of the 1992 Constitution).",
    difficulty: "easy",
  },
  {
    id: "soc-cit-003",
    topicId: "citizenship",
    question: "Human rights are best described as…",
    options: [
      "privileges given only to adults",
      "rights that every person has simply because they are human",
      "rules made by chiefs",
      "rights that can be bought",
    ],
    correctOption: 1,
    explanation: "Human rights are basic rights and freedoms that belong to every person, such as the right to life and freedom of expression.",
    difficulty: "easy",
  },
  {
    id: "soc-cit-004",
    topicId: "citizenship",
    question: "Love for and loyalty to one's country is called…",
    options: ["nepotism", "patriotism", "tribalism", "materialism"],
    correctOption: 1,
    explanation: "Patriotism is love for and devotion to one's country. Nepotism is favouring relatives, and tribalism is loyalty to one's ethnic group above the nation.",
    difficulty: "easy",
  },
  {
    id: "soc-cit-005",
    topicId: "citizenship",
    question: "Which of the following is a civic responsibility?",
    options: [
      "Obeying the laws of the country",
      "Refusing to register to vote",
      "Damaging public property during protests",
      "Evading taxes",
    ],
    correctOption: 0,
    explanation: "Obeying the law is a basic civic responsibility. The other options harm society.",
    difficulty: "easy",
  },

  // Development and Cooperation
  {
    id: "soc-dev-001",
    topicId: "development",
    question: "The Economic Community of West African States (ECOWAS) was established in…",
    options: ["1957", "1963", "1975", "2002"],
    correctOption: 2,
    explanation: "ECOWAS was established by the Treaty of Lagos in May 1975 to promote economic cooperation among West African countries.",
    difficulty: "medium",
  },
  {
    id: "soc-dev-002",
    topicId: "development",
    question: "Human resources refer to…",
    options: [
      "minerals found underground",
      "the knowledge, skills and abilities of people",
      "money kept in banks",
      "forests and rivers",
    ],
    correctOption: 1,
    explanation: "Human resources are the skills, knowledge, energy and talents of people that can be used for development.",
    difficulty: "easy",
  },
  {
    id: "soc-dev-003",
    topicId: "development",
    question: "Which of the following is a renewable natural resource when properly managed?",
    options: ["Gold", "Bauxite", "Crude oil", "Forests"],
    correctOption: 3,
    explanation: "Forests can regrow if trees are replanted and harvested sustainably. Gold, bauxite and crude oil are non-renewable.",
    difficulty: "easy",
  },
  {
    id: "soc-dev-004",
    topicId: "development",
    question: "The movement of skilled professionals such as doctors and nurses from a country to work abroad is known as…",
    options: ["rural–urban migration", "brain drain", "urbanisation", "seasonal migration"],
    correctOption: 1,
    explanation: "Brain drain is the emigration of highly skilled or educated people, which deprives the home country of their expertise.",
    difficulty: "easy",
  },
  {
    id: "soc-dev-005",
    topicId: "development",
    question: "The African Union (AU) replaced which organisation?",
    options: [
      "The Economic Community of West African States",
      "The Organisation of African Unity",
      "The Commonwealth",
      "The United Nations",
    ],
    correctOption: 1,
    explanation: "The AU was launched in 2002 as the successor to the Organisation of African Unity (OAU), which had been formed in 1963.",
    difficulty: "medium",
  },
  {
    id: "soc-dev-006",
    topicId: "development",
    question: "Where is the headquarters of the African Union?",
    options: ["Accra", "Abuja", "Addis Ababa", "Nairobi"],
    correctOption: 2,
    explanation: "The African Union's headquarters is in Addis Ababa, Ethiopia.",
    difficulty: "easy",
  },
]);
